In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
app=pd.read_csv("C:\\Users\\Admin\\Desktop\\datasets\\project\\AppleStore.csv")
print(app)


      Unnamed: 0          id  \
0              1   281656475   
1              2   281796108   
2              3   281940292   
3              4   282614216   
4              5   282935706   
5              6   283619399   
6              7   283646709   
7              8   284035177   
8              9   284666222   
9             10   284736660   
10            11   284791396   
11            12   284815117   
12            13   284815942   
13            14   284847138   
14            15   284862767   
15            16   284876795   
16            17   284882215   
17            18   284910350   
18            20   284993459   
19            21   285005463   
20            22   285946052   
21            23   285994151   
22            24   286058814   
23            25   286070473   
24            27   286799607   
25            28   286906691   
26            29   286911400   
27            31   288113403   
28            32   288120394   
29            33   288419283   
...     

In [3]:
x=app.iloc[:,[3,5,6,10,11,12,13,14,15,16]]
y=app.iloc[:,8].values
x

size_bytes  price  rating_count_tot       ver cont_rating  \
0      100788224   3.99             21292     6.3.5          4+   
1      158578688   0.00            161065     8.2.2          4+   
2      100524032   0.00            188583     5.0.0          4+   
3      128512000   0.00            262241    5.10.0         12+   
4       92774400   0.00            985920     7.5.1          4+   
5       10485713   0.99              8253       1.8          4+   
6      227795968   0.00            119487    6.12.0          4+   
7      130242560   0.00           1126879     8.4.1         12+   
8       49250304   9.99              1117     3.6.6          4+   
9       70023168   3.99              7885     4.0.4          4+   
10      49618944   4.99             76720    4.10.1          4+   
11     227547136   7.99            105776    5.19.0          4+   
12     179979264   0.00            479440      27.0         17+   
13     160925696   0.00            119773     7.3.8          4+   
14      55153664   4.99              6340     4.0.3          4+   
15     207907840   0.00             56194      21.1          4+   
16     389879808   0.00           2974676      95.0          4+   
17     167407616   0.00            223885   11.15.0         12+   
18     147093504   0.00            402925    11.0.3         12+   
19      10735026   2.99             31456     1.0.0          4+   
20      70707916   1.99              2929       3.3          4+   
21       6169600   2.99             11447     5.2.6          4+   
22     130583552   0.00            137951       6.9          4+   
23      71203840   5.99                 8     9.0.5          4+   
24      11423008   3.99              3241     2.1.3          4+   
25     188017664   0.00              5795     8.4.1          4+   
26       4765696   0.00             42316     2.0.6          9+   
27     287933440   0.00            123215    10.5.4          4+   
28       4263936   4.99               782     1.9.8          4+   
29     172772352   9.99              3449     3.4.1          4+   
...          ...    ...               ...       ...         ...   
7167   177498112   0.00                 1     1.0.1          4+   
7168    89188352   0.00                 3     1.0.1          4+   
7169    32685056   2.99                 9     1.0.1          4+   
7170    26077184   0.00                39       1.3          9+   
7171   143346688   0.00                10       1.0          4+   
7172   242505728   3.99                55       1.4          4+   
7173    18164736   0.99                 0       1.1          4+   
7174   169535488   0.00                14     1.3.0          4+   
7175    64244736   0.00                41       1.3          4+   
7176   184324096   0.00                 0     1.0.1          4+   
7177    33946624   0.00                11     1.1.0          4+   
7178   327731200   0.99                 0       1.1          4+   
7179   113382400   0.00               279    0.6.41          4+   
7180    94008320   0.00                26     1.0.5          9+   
7181   178160640   0.99                 0       1.0          9+   
7182     9362432   0.00                 0     1.0.3          4+   
7183    57349120   3.99               292  2.0.20.1          9+   
7184   171944960   0.00                 0       1.0          9+   
7185   208026624   0.99                 0       1.0          9+   
7186    85580800   0.00                 1     1.0.1          4+   
7187    52342784   0.00                23       1.0          4+   
7188   168774656   0.00                18     1.0.0         12+   
7189   537462784   0.99                 0     2.1.0          9+   
7190    22999040   2.99                97       1.0          4+   
7191    27853824   2.99                11     1.1.1         17+   
7192   126644224   0.00               142       1.3          4+   
7193   120760320   0.00                30       0.9          4+   
7194   111322112   1.99                15     1.0.2  

In [4]:
app.isnull().sum()

Unnamed: 0          0
id                  0
track_name          0
size_bytes          0
currency            0
price               0
rating_count_tot    0
rating_count_ver    0
user_rating         0
user_rating_ver     0
ver                 0
cont_rating         0
prime_genre         0
sup_devices.num     0
ipadSc_urls.num     0
lang.num            0
vpp_lic             0
dtype: int64

In [5]:
app_dummy=pd.get_dummies(app['prime_genre'])
app_dummy1=pd.get_dummies(app['cont_rating'])
app_dummy=pd.concat([app,app_dummy,app_dummy1],axis=1)
app_dummy.isnull().sum()


Unnamed: 0           0
id                   0
track_name           0
size_bytes           0
currency             0
price                0
rating_count_tot     0
rating_count_ver     0
user_rating          0
user_rating_ver      0
ver                  0
cont_rating          0
prime_genre          0
sup_devices.num      0
ipadSc_urls.num      0
lang.num             0
vpp_lic              0
Book                 0
Business             0
Catalogs             0
Education            0
Entertainment        0
Finance              0
Food & Drink         0
Games                0
Health & Fitness     0
Lifestyle            0
Medical              0
Music                0
Navigation           0
News                 0
Photo & Video        0
Productivity         0
Reference            0
Shopping             0
Social Networking    0
Sports               0
Travel               0
Utilities            0
Weather              0
12+                  0
17+                  0
4+                   0
9+         

In [6]:
x=app_dummy.iloc[:,3:]
y=app.iloc[:,8].values
x=x.drop(['currency','rating_count_ver','user_rating','user_rating_ver','prime_genre','cont_rating','ver'],axis=1)
x

size_bytes  price  rating_count_tot  sup_devices.num  ipadSc_urls.num  \
0      100788224   3.99             21292               38                5   
1      158578688   0.00            161065               37                5   
2      100524032   0.00            188583               37                5   
3      128512000   0.00            262241               37                5   
4       92774400   0.00            985920               37                5   
5       10485713   0.99              8253               47                5   
6      227795968   0.00            119487               37                0   
7      130242560   0.00           1126879               37                4   
8       49250304   9.99              1117               37                5   
9       70023168   3.99              7885               38                0   
10      49618944   4.99             76720               38                4   
11     227547136   7.99            105776               37                0   
12     179979264   0.00            479440               37                4   
13     160925696   0.00            119773               37                0   
14      55153664   4.99              6340               38                5   
15     207907840   0.00             56194               37                1   
16     389879808   0.00           2974676               37                1   
17     167407616   0.00            223885               37                5   
18     147093504   0.00            402925               37                3   
19      10735026   2.99             31456               47                0   
20      70707916   1.99              2929               43                0   
21       6169600   2.99             11447               40                5   
22     130583552   0.00            137951               37                2   
23      71203840   5.99                 8               37                5   
24      11423008   3.99              3241               43                2   
25     188017664   0.00              5795               37                5   
26       4765696   0.00             42316               38                0   
27     287933440   0.00            123215               37                5   
28       4263936   4.99               782               43                1   
29     172772352   9.99              3449               37                5   
...          ...    ...               ...              ...              ...   
7167   177498112   0.00                 1               38                4   
7168    89188352   0.00                 3               38                5   
7169    32685056   2.99                 9               37                0   
7170    26077184   0.00                39               37                1   
7171   143346688   0.00                10               40                0   
7172   242505728   3.99                55               40                5   
7173    18164736   0.99                 0               37                0   
7174   169535488   0.00                14               37                5   
7175    64244736   0.00                41               37                5   
7176   184324096   0.00                 0               40                4   
7177    33946624   0.00                11               37                5   
7178   327731200   0.99                 0               37                5   
7179   113382400   0.00               279               37                4   
7180    94008320   0.00                26               37                4   
7181   178160640   0.99                 0               40                5   
7182     9362432   0.00                 0               37                0   
7183    57349120   3.99               292               40                5   
7184   171944960   0.00                 0               40                5   
7185   208026624   0.99                 0               

In [7]:
from sklearn import preprocessing
standard=preprocessing.StandardScaler().fit(x)
standard.transform(x)

array([[-0.27380615,  0.38812569,  0.11090232, ..., -0.30757237,
         0.78962366, -0.39866928],
       [-0.11291148, -0.29596024,  1.95647669, ..., -0.30757237,
         0.78962366, -0.39866928],
       [-0.27454169, -0.29596024,  2.31982667, ..., -0.30757237,
         0.78962366, -0.39866928],
       ...,
       [-0.24447871,  0.04522548, -0.17004096, ..., -0.30757237,
        -1.26642608,  2.50834474],
       [-0.283696  , -0.29596024, -0.16911668, ..., -0.30757237,
        -1.26642608, -0.39866928],
       [-0.30134036, -0.29596024, -0.17019941, ..., -0.30757237,
         0.78962366, -0.39866928]])

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=45)

In [9]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [10]:
y_pred=regressor.predict(x_test)
y_pred


array([3.24242541, 1.30493389, 3.74154719, ..., 3.46637751, 4.03246573,
       3.98908323])

In [11]:
y_test

array([5. , 5. , 3. , ..., 4. , 5. , 4.5])

In [12]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

0.11376951405618707


In [13]:
from sklearn import tree
from sklearn.tree import DecisionTreeRegressor
regression_tree = DecisionTreeRegressor(min_samples_split=.05)
regression_tree.fit(x,y)
y_pred=regression_tree.predict(x)

In [18]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 100, random_state=45)
regressor.fit(x,y)
y_pred_rf=regressor.predict(x)


In [15]:
from sklearn.metrics import r2_score
r2_score(y,y_pred)

0.8373622878777811

In [19]:
from sklearn.metrics import r2_score
r2_score(y,y_pred_rf)

0.9763600417325035